#!/bin/sh

# export GST_DEBUG=4

gst-launch-1.0 -vef \
     flvmux name=mux \
   ! rtmpsink location="rtmp://127.0.0.1:1935/rtmp2rtsp/stream" \
     videotestsrc \
   !     video/x-raw,width=320,height=240,framerate=30/1 \
   ! videoscale \
   ! videorate \
   ! videoconvert \
   ! timeoverlay \
   ! x264enc key-int-max=30 \
   !     video/x-h264,profile=baseline \
   ! h264parse config-interval=1 \
   ! mux.video \
     audiotestsrc \
   ! faac \
   ! aacparse \
   ! mux.audio
