#!/bin/sh

# export GST_DEBUG=4

gst-launch-1.0 -vef \
    rtspsrc location="rtsp://127.0.0.1:8554/stream" name=src \
    src. \
  ! queue \
  ! rtph264depay \
  ! h264parse \
  ! avdec_h264 \
  ! autovideosink \
    src. \
  ! queue \
  ! rtpmp4adepay \
  ! aacparse \
  ! faad \
  ! autoaudiosink
